CREATE TABLE stocks(
    company_name VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    description VARCHAR(255),
    exchange VARCHAR(255) NOT NULL,
    exchange_short_name VARCHAR(255) NOT NULL,
    fwd_pe_ratio int,
    industry VARCHAR(255) NOT NULL,
    is_eft BOOLEAN NOT NULL,
    market_cap BIGINT NOT NULL,
    pe_ratio int,
    ps_ratio int,
    sector VARCHAR(255),
    ticker VARCHAR(10) PRIMARY KEY NOT NULL,
    website VARCHAR(255)
);

CREATE TABLE financial_statements_growth_annual(
    date DATE NOT NULL,
    growth_cost_and_expenses  decimal,
    growth_cost_of_revenue  decimal,
    growth_depreciation_and_amortization  decimal,
    growth_ebitda  decimal,
    growth_ebitda_ratio  decimal,
    growth_eps  decimal,
    growth_eps_diluted  decimal,
    growth_general_and_administrative_expenses  decimal,
    growth_gross_profit  decimal,
    growth_gross_profit_ratio  decimal,
    growth_income_before_tax  decimal,
    growth_income_before_tax_ratio  decimal,
    growth_income_tax_expense decimal,
    growth_interest_expense  decimal,
    growth_net_income  decimal,
    growth_net_income_ratio decimal,
    growth_operating_expenses  decimal,
    growth_operating_income  decimal,
    growth_operating_income_ratio  decimal,
    growth_other_expenses  decimal,
    growth_research_and_development_expenses  decimal,
    growth_revenue  decimal,
    growth_selling_and_marketing_expenses  decimal,
    growth_total_other_income_expenses_net  decimal,
    growth_weighted_average_shs_out  decimal,
    growth_weighted_average_shs_out_dil decimal,
    period  VARCHAR(255) NOT NULL,
    quarterly_id VARCHAR(255) PRIMARY KEY NOT NULL,
    ticker VARCHAR(10) REFERENCES stocks(ticker),
);

CREATE TABLE financial_growth_quarterly(
    asset_growth decimal,
    book_valueper_share_growth decimal,
    date DATE NOT NULL,
    debt_growth decimal,
    dividendsper_share_growth decimal,
    ebitgrowth decimal,
    epsdiluted_growth decimal,
    epsgrowth decimal,
    five_y_dividendper_share_growth_per_share decimal,
    five_y_net_income_growth_per_share decimal,
    five_y_operating_cf_growth_per_share decimal,
    five_y_revenue_growth_per_share decimal,
    five_y_shareholders_equity_growth_per_share decimal,
    free_cash_flow_growth decimal,
    gross_profit_growth decimal,
    inventory_growth decimal,
    net_income_growth decimal,
    operating_cash_flow_growth decimal,
    operating_income_growth decimal,
    period VARCHAR(255) NOT NULL,
    quarterly_id VARCHAR(255) PRIMARY KEY NOT NULL,
    rdexpense_growth decimal,
    receivables_growth decimal,
    revenue_growth decimal,
    sgaexpenses_growth decimal,
    ten_y_dividendper_share_growth_per_share decimal,
    ten_y_net_income_growth_per_share decimal,
    ten_y_operating_cf_growth_per_share decimal,
    ten_y_revenue_growth_per_share decimal,
    ten_y_shareholders_equity_growth_per_share decimal,
    three_y_dividendper_share_growth_per_share decimal,
    three_y_net_income_growth_per_share decimal,
    three_y_operating_cf_growth_per_share decimal,
    three_y_revenue_growth_per_share decimal,
    three_y_shareholders_equity_growth_per_share decimal,
    ticker VARCHAR(10) REFERENCES stocks(ticker),
    weighted_average_shares_diluted_growth decimal,
    weighted_average_shares_growth decimal,
);

CREATE TABLE financial_quarterly(
    accepted_date DATE NOT NULL,
    calendar_year VARCHAR(4),
    cik VARCHAR(255),
    cost_and_expenses decimal,
    cost_of_revenue decimal,
    date DATE NOT NULL,
    depreciation_and_amortization decimal,
    ebitda decimal,
    ebitdaratio decimal,
    eps decimal,
    epsdiluted decimal,
    filling_date DATE NOT NULL,
    final_link VARCHAR(255),
    general_and_administrative_expenses decimal,
    gross_profit decimal,
    gross_profit_ratio decimal,
    income_before_tax decimal,
    income_before_tax_ratio decimal,
    income_tax_expense decimal,
    interest_expense decimal,
    interest_income decimal,
    link VARCHAR(255),
    net_income decimal,
    net_income_ratio decimal,
    operating_expenses decimal,
    operating_income decimal,
    operating_income_ratio decimal,
    other_expenses decimal,
    period VARCHAR(255) NOT NULL,
    quarterly_id VARCHAR(255) PRIMARY KEY NOT NULL,
    reported_currency VARCHAR(255),
    research_and_development_expenses decimal,
    revenue decimal,
    selling_and_marketing_expenses decimal,
    selling_general_and_administrative_expenses decimal,
    ticker VARCHAR(10) REFERENCES stocks(ticker),
    total_other_income_expenses_net decimal,
    weighted_average_shs_out decimal,
    weighted_average_shs_out_dil decimal
)

